openapi: "3.0.3"

info:
  version: "2.0"
  title: API Simulator
  description: |
    # Overview

    An 'api simulator' to do performance tests on the API Platform.
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/
  description: Production

components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.2.0+json"
        ]
      required: true
    contentTypeHeader:
      name: Content-Type
      in: header
      schema:
        type: string
        enum: [
          "application/json"
        ]
      required: true
    latencyPathParam:
      name: latency
      in: path
      description: The latency of the service to respond in milliseconds.
      required: true
      schema:
        type: integer
        format: int32
        example: 1073741823
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
    userRestricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows: 
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:performance-tests: Performance tests

paths:
  /api-simulator/user:
    post:
      summary: User API with Post
      description: A simple user endpoint that allows POST requests.
      tags:
        - api-simulator
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/contentTypeHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                $ref: './examples/user-api-with-post-example-1.json'
      security:
        - userRestricted:
          - read:performance-tests
          
    put:
      summary: User API with Put
      description: A simple user endpoint that allows PUT requests.
      tags:
        - api-simulator
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/contentTypeHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                $ref: './examples/user-api-with-put-example-1.json'
      security:
        - userRestricted:
          - read:performance-tests
              
  /api-simulator/user/data/{data}:
    get:
      summary: User API with data
      description: A simple user endpoint that return configurable amounts of data.
      tags:
        - api-simulator
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - name: data
          in: path
          description: The number of characters to return in the response.
          required: true
          schema:
            type: integer
            format: int32
            example: 1073741823
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                $ref: './examples/user-api-with-data-example-1.json'
      security:
        - userRestricted:
          - read:performance-tests

  /api-simulator/user/latency/{latency}:
    get:
      summary: User API with latency
      description: A simple user endpoint that return with a configurable latency.
      tags:
        - api-simulator
      parameters:
        - $ref: '#/components/parameters/latencyPathParam'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                $ref: './examples/user-api-with-latency-example-1.json'
      security:
        - userRestricted:
          - read:performance-tests

  /api-simulator/application/accepted/latency/{latency}:
    post:
      summary: A general application restricted endpoint that returns an ACCEPTED response.
      description: |
        An endpoint that can be used to test calling an application restricted endpoint using POST
        and returning an ACCEPTED response with a given latency.
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/latencyPathParam'
      responses:
        202:
          description: "ACCEPTED Response"
      security:
        - applicationRestricted: []
