#%RAML 1.0
---

title: API Simulator
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/api-simulator:
  /user:
    post:
      displayName: User API with Post
      description: A simple user endpoint that allows POST requests.
      is: [headers.acceptHeader]
      (annotations.scope): "read:performance-tests"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:performance-tests" ] } ]
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/user-api-with-post-example-1.json
    put:
      displayName: User API with Put
      description: A simple user endpoint that allows PUT requests.
      is: [headers.acceptHeader]
      (annotations.scope): "read:performance-tests"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:performance-tests" ] } ]
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/user-api-with-put-example-1.json
    /latency:
      /{latency}:
        uriParameters:
          latency:
            description: The latency of the service to respond in milliseconds.
            type: number
            example: 2234567890
        get:
          displayName: User API with latency
          description: A simple user endpoint that return with a configurable latency.
          is: [headers.acceptHeader]
          (annotations.scope): "read:performance-tests"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:performance-tests" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/user-api-with-latency-example-1.json
    /data:
      /{data}:
        uriParameters:
          data:
            description: The number of characters to return in the response.
            type: number
            example: 2234567890
        get:
          displayName: User API with data
          description: A simple user endpoint that return configurable amounts of data.
          is: [headers.acceptHeader]
          (annotations.scope): "read:performance-tests"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:performance-tests" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/user-api-with-data-example-1.json
